baseurl = "https://gabriel.llera.eu/"
languageCode = "es-es"
title = "gllera's blog"
googleAnalytics = "UA-28079199-1"
paginate = 6

[params]
    rssUrl = "http://feeds.feedburner.com/llera"

[outputs]
    home = [ "HTML", "RSS" ]
    page = [ "HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"

[permalinks]
  post = "/:year/:month/:day/:slug/"