baseurl = "https://example.org/"
languageCode = "en-us"
title = "gllera's blog"
googleAnalytics = ""
paginate = 6
summaryLength = 100

[params]
    rssUrl = "http://feeds.feedburner.com/llera"

[outputs]
    home = [ "HTML", "RSS" ]
    page = [ "HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""

[permalinks]
  post = "/:year/:month/:day/:slug/"