version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-stretch

    steps:
      - checkout
      - run: bash -e .circleci/build-hugo.sh
      - run: npm ci
      - run: bash -e .circleci/git-init.sh
      - run: npm start
      - run: bash -e .circleci/deploy.sh