image: buildpack-deps:stable-scm

variables:
  HUGO_VERSION: "0.49"
  NODE_VERSION: "10.12.0"

cache:
  key: "blog_${NODE_VERSION}_${HUGO_VERSION}"
  paths:
  - .cache

build:
    stage: build
    script:
      - bash -e .ci/build.sh
